version: "3.8"

services:
  app:
    image: kuronosu/animeflv-api
    build: .
    environment:
      AnimeFLVConnectionString: "mongodb://db:27017"
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: mongo
